# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build on Arch with code analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'c-cpp' ]

    steps:
    - name: Install QT6
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.6.*
        modules: qtpdf
        
    - name: Install libmagick++-7
      run:  |
        deb http://www.deb-multimedia.org sid main  &&
        sudo apt-get update -oAcquire::AllowInsecureRepositories=true &&
        sudo apt-get install deb-multimedia-keyring &&
        sudo apt-get install libmagick++-7-dev
      
    -   name: Install other dependencies
        run: |
          sudo apt-get update -yq &&
          sudo apt-get install libssh-dev libtesseract-dev libpoppler-cpp-dev
          
    - uses: actions/checkout@v4
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    - name: Prepare for Build
      run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --target all --config Release -- -j4
        
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"



