# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Install QT6
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.6.*
        modules: qtpdf
      
    -   name: Install dependencies
        run: |
          sudo apt-get update -yq &&
          sudo apt-get install imagemagick libssh-dev libtesseract-dev libpoppler-dev
          
    - uses: actions/checkout@v3

    - name: Prepare for Build
      run: cmake ${{github.workspace}}

    - name: Build
      # Build your program with the given configuration
      run: cmake -DCMAKE_BUILD_TYPE=Release ${{github.workspace}}

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
     # run: ctest -C ${{env.BUILD_TYPE}}

